version: '3.8'

services:
  main:
    image: rengumin/shopiew-main:latest
    build:
      context: .
      target: main
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - shopiew-network

  seller:
    image: rengumin/shopiew-seller:latest

    build:
      context: .
      target: seller
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - shopiew-network

  admin:
    image: rengumin/shopiew-admin:latest
    build:
      context: .
      target: admin
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - shopiew-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - main
      - seller
      - admin
    networks:
      - shopiew-network

networks:
  shopiew-network:
    driver: bridge
