name: Detect and Push changes to Docker Hub

on:
  push:
    branches: [main]

jobs:
  detect-changes:
   
    runs-on: ubuntu-latest
    outputs:
      main: ${{ steps.filter.outputs.main }}
      seller: ${{ steps.filter.outputs.seller }}
    steps:
      - uses: actions/checkout@v4
        with: 
           fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            main:
              - 'apps/main/**'
            seller:
              - 'apps/seller/**'

  push-shopiew-main:
    needs: detect-changes
    if: needs.detect-changes.outputs.main == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying @shopiew/main"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/main/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shopiew-main:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shopiew-main:${{ steps.short_sha.outputs.short_sha }}

  push-shopiew-seller:
    needs: detect-changes
    if: needs.detect-changes.outputs.seller == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying @shopiew/seller"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/seller/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shopiew-seller:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shopiew-seller:${{ steps.short_sha.outputs.short_sha }}
