# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - shopiew-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --filter=@shopiew/main

      - name: Build with turbo
        run: pnpm turbo run build --filter=@shopiew/main
      - name: Go to @shopiew/main
        run: |
          cd apps/main
          cp -r public .next/standalone/apps/main/ && cp -r .next/static .next/standalone/apps/main/.next/
          cd .next/standalone/apps/main

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shopiew-main'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2F80BEC02DF4DD18BD6782811F0060E }}